---
- name: Yum update
  shell: dnf clean packages && yum update -y && dnf clean packages
  tags: common

- name: Install EPEL release package for RHEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: latest
  when: ansible_distribution == 'Red Hat Enterprise Linux'
  tags: common

- name: Install system build dependencies
  yum: name={{ item }} state=present
  with_items: "{{ system_build_dependencies }}"
  tags: common

- name: Write these values to /home/{{os.user.name}}/.bashrc
  blockinfile:
    dest: /home/{{os.user.name}}/.bashrc
    block: |
      export PYENV_ROOT="/home/{{os.user.name}}/.pyenv"
      export PATH="/home/{{os.user.name}}/.pyenv/bin:${PATH}"
      eval "$(pyenv init -)"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - rdb'
    insertbefore: EOF
    create: yes 
