Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    # TODO: re-enable rake after testing
    - 'lib/**/*.rake'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'marvel_styling-rails.gemspec'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'Capfile'
    - 'Guardfile'
    - 'lib/kee_import/**'
    - 'lib/price_import/**'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i':    ()

Style/Lambda:
  Exclude:
    - 'app/models/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'app/models/*'

MethodLength:
  Exclude:
    - 'spec/**/*'

ClassLength:
  Exclude:
    - 'spec/**/*'

AbcSize:
  Exclude:
    - 'spec/**/*'

BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['\A#  index_']

#################### Layout ###########################

Layout/AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  StyleGuide: '#indent-public-private-protected'
  Enabled: true
  VersionAdded: '0.49'
  EnforcedStyle: indent
  SupportedStyles:
    - outdent
    - indent
  # By default, the indentation width from Layout/IndentationWidth is used
  # But it can be overridden by setting this parameter
  IndentationWidth: ~
