# Language locales
dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "vendor/**/*"
  - "*.key"
  - "*.enc"
  - "*.mk"
  - ".DS_Store"
  - ".env"
  - ".flaskenv"
  - "*.pyc"
  - "*.pyo"
  - "env/"
  - "env*"
  - "dist/"
  - "build/"
  - "*.egg"
  - "*.egg-info/"
  - "_mailinglist"
  - ".tox/"
  - ".cache/"
  - ".pytest_cache/"
  - ".idea/"
  - "docs/_build/"
  - ".typo-ci.yml"
  - ".vscode"
  - "env-packages"
  - "htmlcov/"
  - ".coverage"
  - ".coverage.*"
  - "*,cover"


# Any typos we should ignore?
excluded_words:
  - centos
  - computecanada
  - fridman
  - ian
  - mzxmls
  - percel
  - rdbclient
  - snoskov
  - sqlalchemy
  - swacker
  - typoci
  - ucalgary

# Would you like filenames to also be spellchecked?
spellcheck_filenames: true
