api:
  build: .
  container_name: api
  command: /etc/entrypoint.sh
  volumes:
    - .:/api
  ports:
    - 3000:3000
  links:
    - db
db:
  container_name: db
  image: postgres
  environment:
    POSTGRES_PASSWORD: postgres
