project:
  name: rdb
  email: bot@westgrid.ca

os:
  user:
    name: "{{ lookup('env','RDB_VM_USER') or 'ubuntu' }}"
    group: "{{ lookup('env','RDB_VM_USER') or 'ubuntu' }}"

rdb:
  domain: "{{ lookup('env','RDB_DOMAIN') or 'staging.rdb.c3.ca' }}"
  domains: "{{ (lookup('env','RDB_DOMAINS') or 'api.staging.rdb.c3.ca').split(',') }}"
  ip: "{{ ansible_default_ipv4.address }}"
  repo:
    api: git@github.com:LSARP/api.git
    frontend: git@github.com:LSARP/frontend.git
  parent_path: /var/www
  root_path: /var/www/rdb
  api_root_path: /var/www/rdb/api
  frontend_root_path: /var/www/rdb/frontend
  frontend_root_path: /var/www/rdb/frontend

python:
  install_version: "{{ lookup('env','RDB_PYTHON_VERSION') or '3.8.5' }}"
  main_version: 3
  bin_path: /usr/local/bin

centos_version: 8 
system_build_dependencies:
  - bash-completion
  - libbz2-dev
  - libsqlite3-dev
  - libreadline6-dev
  - libffi-dev
  - python3-dev
  - libjpeg-dev
  - libjpeg8-dev
  - python3-pip
  - python3-psycopg2
  - git
  - curl
  - wget
  - libssl-dev
  - build-essential
  - liblzma-dev
  - make
  - zlib1g-dev
  - python3-dev
  - libevent-dev
  - libblas-dev
  - libatlas-base-dev
  - python3-venv
  - libpq-dev
  - postgresql-contrib
