---
- name: Patch SELinux
  command: setsebool httpd_can_network_connect 1
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags: nginx

- name: Install certbot-nginx nginx
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - certbot-nginx
    - nginx
  tags: nginx

- name: Setup letsencrypt local directory
  file:
    path: /etc/letsencrypt/live/{{ domain }}
    state: directory
  tags: nginx

- name: Generate ssl certificates with OpenSSL
  shell: /usr/bin/openssl req -x509 -newkey rsa:4096 -sha256 \
    -days 36500 -nodes -keyout /etc/letsencrypt/live/{{ domain }}/privkey.pem \
    -out /etc/letsencrypt/live/{{ domain }}/fullchain.pem -subj '/CN={{ domain }}/O=LSARP./C=CA'
  tags: nginx

- name: Create /etc/nginx/nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags: nginx

- name: Write default.conf.j2 into /etc/nginx/conf.d/default.conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  tags: nginx

- name: Generate SSL certificates with Letsencrypt
  shell: /usr/bin/letsencrypt certonly --renew-by-default -n --nginx \
        -m {{ project.email }} --agree-tos -d {{ domain }} --rsa-key-size 4096
  ignore_errors: yes
  when: use_letsencrypt == 'yes'
  tags: nginx

- name: Enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
  tags: nginx

- name: Jump start nginx
  service:
    name: nginx
    state: restarted
  tags: nginx

- name: Restart nginx and rdb stack
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - api
    - front
    - nginx
  tags: nginx

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal-{{ domain }}
    special_time: weekly
    job: /usr/bin/certbot --nginx -d {{ domain }} --no-redirect --register-unsafely-without-email --agree-tos --rsa-key-size 4096
  tags: nginx
