"""Define index for access token

Revision ID: 17f7dba3a1a4
Revises: 2ae529e24986
Create Date: 2020-06-08 16:28:57.750557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f7dba3a1a4'
down_revision = '2ae529e24986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_access_token'), 'sessions', ['access_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_access_token'), table_name='sessions')
    # ### end Alembic commands ###
