"""Define timestamp columns (i.e created_at and updated_at)

Revision ID: 2ae529e24986
Revises: 6f4a1e04fea6
Create Date: 2020-06-08 16:27:28.626532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae529e24986'
down_revision = '6f4a1e04fea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_updated_at'), 'sessions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_updated_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_column('sessions', 'updated_at')
    op.drop_column('sessions', 'created_at')
    # ### end Alembic commands ###
