"""Add access token column with TEXT datatype

Revision ID: 58dbe451cb20
Revises: b3fd3750e0c0
Create Date: 2020-06-15 13:53:35.237218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58dbe451cb20'
down_revision = 'b3fd3750e0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('access_token', sa.TEXT(), nullable=True))
    op.create_index(op.f('ix_sessions_access_token'), 'sessions', ['access_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_access_token'), table_name='sessions')
    op.drop_column('sessions', 'access_token')
    # ### end Alembic commands ###
