"""Add email to project table

Revision ID: fd47b39850ed
Revises: ccca068a9718
Create Date: 2020-06-09 05:25:16.206200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd47b39850ed'
down_revision = 'ccca068a9718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_email'), 'projects', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_email'), table_name='projects')
    op.drop_column('projects', 'email')
    # ### end Alembic commands ###
