"""Define prototypes table with potential for polymorphic single table inheritance

Revision ID: 4e127ae580da
Revises: ef82c4359bb4
Create Date: 2020-12-10 10:08:15.751288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e127ae580da'
down_revision = 'ef82c4359bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'prototypes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.TEXT(), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('slug', sa.TEXT(), nullable=False),
        sa.Column('content', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_index(
        op.f('ix_prototypes_created_at'), 'prototypes', ['created_at'], unique=False
    )
    op.create_index(op.f('ix_prototypes_slug'), 'prototypes', ['slug'], unique=True)
    op.create_index(op.f('ix_prototypes_type'), 'prototypes', ['type'], unique=False)
    op.create_index(
        op.f('ix_prototypes_updated_at'), 'prototypes', ['updated_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prototypes_updated_at'), table_name='prototypes')
    op.drop_index(op.f('ix_prototypes_type'), table_name='prototypes')
    op.drop_index(op.f('ix_prototypes_slug'), table_name='prototypes')
    op.drop_index(op.f('ix_prototypes_created_at'), table_name='prototypes')
    op.drop_table('prototypes')
    # ### end Alembic commands ###
