"""Change sessions tablename

Revision ID: 6f4a1e04fea6
Revises: db9cc3fc0d2f
Create Date: 2020-06-08 15:41:15.321987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f4a1e04fea6'
down_revision = 'db9cc3fc0d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('access_token', sa.String(length=256), nullable=True),
        sa.Column('tokenized_user', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_table('session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'session',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column(
            'access_token', sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            'tokenized_user',
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id', name='session_pkey'),
    )
    op.drop_table('sessions')
    # ### end Alembic commands ###
