"""Define data types model and table

Revision ID: 25cbeee570b1
Revises: 88f42f5fc666
Create Date: 2020-08-06 05:42:25.354646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cbeee570b1'
down_revision = '88f42f5fc666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('slug', sa.TEXT(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_types_created_at'), 'data_types', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_types_name'), 'data_types', ['name'], unique=False)
    op.create_index(op.f('ix_data_types_project_id'), 'data_types', ['project_id'], unique=False)
    op.create_index(op.f('ix_data_types_slug'), 'data_types', ['slug'], unique=True)
    op.create_index(op.f('ix_data_types_updated_at'), 'data_types', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_types_updated_at'), table_name='data_types')
    op.drop_index(op.f('ix_data_types_slug'), table_name='data_types')
    op.drop_index(op.f('ix_data_types_project_id'), table_name='data_types')
    op.drop_index(op.f('ix_data_types_name'), table_name='data_types')
    op.drop_index(op.f('ix_data_types_created_at'), table_name='data_types')
    op.drop_table('data_types')
    # ### end Alembic commands ###
