"""Define data formats columns on data types table

Revision ID: 3d2d24f3da61
Revises: aa5e4ee929db
Create Date: 2020-08-18 15:31:21.243603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d2d24f3da61'
down_revision = 'aa5e4ee929db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_types', sa.Column('data_formats', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_types', 'data_formats')
    # ### end Alembic commands ###
