"""Remove access token column

Revision ID: b3fd3750e0c0
Revises: db1493af78d5
Create Date: 2020-06-15 13:52:35.234660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fd3750e0c0'
down_revision = 'db1493af78d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_access_token', table_name='sessions')
    op.drop_column('sessions', 'access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sessions',
        sa.Column(
            'access_token', sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.create_index(
        'ix_sessions_access_token', 'sessions', ['access_token'], unique=False
    )
    # ### end Alembic commands ###
