"""Move Metadata shipments association from MZXml to data types

Revision ID: c4d7c3b4a79f
Revises: 93cfd68099ae
Create Date: 2020-08-10 15:09:58.303263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d7c3b4a79f'
down_revision = '93cfd68099ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_shipments', sa.Column('data_type_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_metadata_shipments_data_type_id'), 'metadata_shipments', ['data_type_id'], unique=False)
    op.drop_index('ix_metadata_shipments_mzxml_file_id', table_name='metadata_shipments')
    op.drop_constraint('metadata_shipments_mzxml_file_id_fkey', 'metadata_shipments', type_='foreignkey')
    op.create_foreign_key(None, 'metadata_shipments', 'data_types', ['data_type_id'], ['id'])
    op.drop_column('metadata_shipments', 'mzxml_file_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_shipments', sa.Column('mzxml_file_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'metadata_shipments', type_='foreignkey')
    op.create_foreign_key('metadata_shipments_mzxml_file_id_fkey', 'metadata_shipments', 'mzxml_files', ['mzxml_file_id'], ['id'])
    op.create_index('ix_metadata_shipments_mzxml_file_id', 'metadata_shipments', ['mzxml_file_id'], unique=False)
    op.drop_index(op.f('ix_metadata_shipments_data_type_id'), table_name='metadata_shipments')
    op.drop_column('metadata_shipments', 'data_type_id')
    # ### end Alembic commands ###
