"""Add collaboarators to project table

Revision ID: db1493af78d5
Revises: e3e553821733
Create Date: 2020-06-11 05:10:53.077053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db1493af78d5'
down_revision = 'e3e553821733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'projects',
        sa.Column('collaborators', postgresql.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'collaborators')
    # ### end Alembic commands ###
