"""Rename email to ownder on project table

Revision ID: e3e553821733
Revises: fd47b39850ed
Create Date: 2020-06-11 04:57:36.402955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e553821733'
down_revision = 'fd47b39850ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_owner'), 'projects', ['owner'], unique=False)
    op.drop_index('ix_projects_email', table_name='projects')
    op.drop_column('projects', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'projects', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_projects_email', 'projects', ['email'], unique=False)
    op.drop_index(op.f('ix_projects_owner'), table_name='projects')
    op.drop_column('projects', 'owner')
    # ### end Alembic commands ###
