"""empty message

Revision ID: ef82c4359bb4
Revises: 3d2d24f3da61
Create Date: 2020-08-28 22:14:09.294268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef82c4359bb4'
down_revision = '3d2d24f3da61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'data_format_files_data_type_id_fkey', 'data_format_files', type_='foreignkey'
    )
    op.create_foreign_key(
        None,
        'data_format_files',
        'data_types',
        ['data_type_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint('data_types_project_id_fkey', 'data_types', type_='foreignkey')
    op.create_foreign_key(
        None, 'data_types', 'projects', ['project_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_types', type_='foreignkey')
    op.create_foreign_key(
        'data_types_project_id_fkey', 'data_types', 'projects', ['project_id'], ['id']
    )
    op.drop_constraint(None, 'data_format_files', type_='foreignkey')
    op.create_foreign_key(
        'data_format_files_data_type_id_fkey',
        'data_format_files',
        'data_types',
        ['data_type_id'],
        ['id'],
    )
    # ### end Alembic commands ###
