---
- hosts: rdb
  become: yes
  become_user: root
  gather_facts: yes
  remote_user: centos
  roles:
    - common

  pre_tasks:
    - name: This reboot is a hack to ensure that cloud-init (terraform) and yum locks have been properly executed and released respectively
      reboot:
        reboot_timeout: 10800
