---
- hosts: rdb
  become: yes
  become_user: ubuntu
  gather_facts: yes
  remote_user: ubuntu
  roles:
    - rdb
  pre_tasks:
    - name: Create virtual environment if doesn't already exist
      shell: pipenv shell &
      args:
        chdir: "{{rdb.api_root_path}}"
        executable: /bin/bash

    - name: Activate pipenv for API
      shell: source $(pipenv --venv)/bin/activate && pipenv sync 
      args:
        chdir: "{{rdb.api_root_path}}"
        executable: /bin/bash
