#cloud-config
---
packages:
  - vim
  - screen
  - sudo
users:
  - default
  - name: ubuntu
    groups: users, sys, admin
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD: ALL"
    ssh_authorized_keys:
      -
write_files:
  - path: /etc/environment
    content: |
      ## CREATED BY TERRAFORM CLOUD-INIT START ###

      export FLASK_ENV=production
      export RDB_PYTHON_VERSION=3.8.5
      export PYTHONDONTWRITEBYTECODE=1
      export PIPENV_IGNORE_VIRTUALENVS=1
      export RDB_DOMAIN=${rdb_domain}
      export RDB_DOMAINS=${rdb_domains}
      export RDB_API_USERNAME=${pg_db_user}
      export RDB_API_DATABASE=${pg_db_name}
      export RDB_API_PASSWORD=${pg_db_api_password}
      export RDB_POSTGRES_PASSWORD=${pg_db_password}
      export RDB_POSTGRESQL_DATA_PATH=${pdb_postgresql_data_path}
      export LSARP_DATABASE_URL=${pg_db_protocol}://${pg_db_user}:${pg_db_api_password}@${pg_db_domain}:${pg_db_port}/${pg_db_name}

      ## CREATED BY TERRAFORM CLOUD-INIT END ###
    append: true

runcmd:
  - [ 'sh', '-c', 'echo ${vm_ssh_key_priv} | sed -e "s/-----BEGIN RSA PRIVATE KEY-----/&\n/" -e "s/\S\{64\}/&\n/g" | sed "s/^\s//g" > ~ubuntu/.ssh/id_rsa']
  - [ 'sh', '-c', 'echo ${vm_ssh_key_pub} > ~ubuntu/.ssh/id_rsa.pub']
  - [ 'sh', '-c', 'chown ubuntu:ubuntu -R ~ubuntu/.ssh && chmod 700 ~ubuntu/.ssh && chmod 600 ~ubuntu/.ssh/id_rsa && chmod 600 ~ubuntu/.ssh/id_rsa.pub']
