name: LSARP-CI

on:
  push:

jobs:
  build-and-run-tests:
    name: Build and run LSARP api tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # clones this repository
      - name: Build this instance
        run: |
          sudo make install
          sudo pipenv install --dev

      - name: Lint
        run: |
          source $(pipenv --venv)/bin/activate
          make lint

      - name: Run tests
        env:
          FLASK_ENV: test
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          LSARP_DATABASE_URL: postgresql://postgres:postgres@localhost:5432
        run: |
          source $(pipenv --venv)/bin/activate
          make tests

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432