name: ON-PUSH-TO-ANY-BRANCH-BUILD-RUN-TESTS

on:
  push:
    branches:
      - '*'

jobs:
  build-and-run-tests:
    name: Build and run api tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # clones this repository
        with:
          ref: ${{ github.ref }}
      - name: Build this instance
        run: |
          sudo make install
          sudo pipenv install --dev

      - name: Run tests
        env:
          FLASK_ENV: test
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          LSARP_DATABASE_URL: postgresql://postgres:postgres@localhost:5432
        run: |
          source $(pipenv --venv)/bin/activate
          make tests

      - name: Lint
        run: |
          source $(pipenv --venv)/bin/activate
          make lint

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432